name: Picturepark Github Package publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: git config --global core.longpaths true
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm ci
      - run: npm test
        env:
          TestInstanceUrl: ${{ secrets.TestInstanceUrl }}
          TestIdentityClientId: ${{ secrets.TestIdentityClientId }}
          TestIdentitySecret: ${{ secrets.TestIdentitySecret }}
          TestUsername: ${{ secrets.TestUsername }}
          TestPassword: ${{ secrets.TestPassword }}
          TestIdentityServer: ${{ secrets.TestIdentityServer }}
          TestApiServer: ${{ secrets.TestApiServer }}
          
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@tc4rdpp'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
