name: Picturepark Github Package publish

on:
  push:
    branches:
      - master

jobs:
  picturepark-sdk-v1-angular:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
      
      - name: Increase version picturepark-sdk-v1-angular
        working-directory: ./src/picturepark-sdk-v1-angular
        run: npm version prerelease --preid=pre-${GITHUB_SHA::7}
      - name: Increase version projects/picturepark-sdk-v1-angular
        working-directory: ./src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular
        run: npm version prerelease --preid=pre-${GITHUB_SHA::7}
      - name: Increase version projects/picturepark-sdk-v1-angular-oidc
        working-directory: ./src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-oidc
        run: npm version prerelease --preid=pre-${GITHUB_SHA::7}
      - name: Increase version projects/picturepark-sdk-v1-angular-ui
        working-directory: ./src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui
        run: npm version prerelease --preid=pre-${GITHUB_SHA::7}
      
      - name: Build libraries
        working-directory: ./src/picturepark-sdk-v1-angular
        run: |
          npm run init
          npm run build-libraries
                
      - name: Publish package - picturepark-sdk-v1-angular
        working-directory: ./src/picturepark-sdk-v1-angular/dist/picturepark-sdk-v1-angular
        run: |
          cp package.json package.json.tmp &&
          jq '.repository.url = "git://github.com/tc4rdpp/Picturepark.SDK.TypeScript.git"' package.json.tmp >package.json &&
          rm package.json.tmp
          cat package.json
          npm publish --tag pre
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_auth_token }}     
      - name: Publish package - picturepark-sdk-v1-angular-oidc
        working-directory: ./src/picturepark-sdk-v1-angular/dist/picturepark-sdk-v1-angular-oidc
        run: |
          cp package.json package.json.tmp &&
          jq '.repository.url = "git://github.com/tc4rdpp/Picturepark.SDK.TypeScript.git"' package.json.tmp >package.json &&
          rm package.json.tmp
          cat package.json
          npm publish --tag pre
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_auth_token }}
      - name: Publish package - picturepark-sdk-v1-angular-ui
        working-directory: ./src/picturepark-sdk-v1-angular/dist/picturepark-sdk-v1-angular-ui
        run: |
          cp package.json package.json.tmp &&
          jq '.repository.url = "git://github.com/tc4rdpp/Picturepark.SDK.TypeScript.git"' package.json.tmp >package.json &&
          rm package.json.tmp
          cat package.json
          npm publish --tag pre
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_auth_token }}
  
  # TODO: Solve the empty GITHUB_SHA issue
  #picturepark-sdk-v1-fetch:
  #  runs-on: [windows-latest]
  #  strategy:
  #    matrix:
  #      node-version: [12.x]
  #  steps:
  #    - run: git config --global core.longpaths true
  #    - uses: actions/checkout@v2
  #    - name: Use Node.js ${{ matrix.node-version }}
  #      uses: actions/setup-node@v1
  #      with:
  #        node-version: ${{ matrix.node-version }}
  #        registry-url: https://npm.pkg.github.com/
  #    
  #    - name: Increase version
  #      working-directory: ./src/picturepark-sdk-v1-fetch
  #      run: npm version prerelease --preid=pre-${GITHUB_SHA::7}
  #    
  #    - name: Build fetch
  #      run: |
  #        echo HELLO ${GITHUB_SHA}
  #        npm install
  #        npm run build:fetch
  #        
  #    - name: Publish package - picturepark-sdk-v1-fetch
  #      working-directory: ./src/picturepark-sdk-v1-fetch
  #      run: npm publish --tag pre
  #      env:
  #        NODE_AUTH_TOKEN: ${{ secrets.npm_auth_token }}
  #        
  #picturepark-sdk-v1-pickers:
  #  runs-on: [windows-latest]
  #  strategy:
  #    matrix:
  #      node-version: [12.x]
  #  steps:
  #    - run: git config --global core.longpaths true
  #    - uses: actions/checkout@v2
  #    - name: Use Node.js ${{ matrix.node-version }}
  #      uses: actions/setup-node@v1
  #      with:
  #        node-version: ${{ matrix.node-version }}
  #        registry-url: https://npm.pkg.github.com/
  #    
  #    - name: Increase version
  #      working-directory: ./src/picturepark-sdk-v1-pickers
  #      run: npm version prerelease --preid=pre-${GITHUB_SHA::7}
  #      
  #    - name: Build pickers
  #      run: |
  #        npm install
  #        npm run build:pickers
  #        
  #    - name: Publish package - picturepark-sdk-v1-pickers
  #      working-directory: ./src/picturepark-sdk-v1-pickers
  #      run: npm publish --tag pre
  #      env:
  #        NODE_AUTH_TOKEN: ${{ secrets.npm_auth_token }}
